import { Species } from '../types';

export const seedSpecies: Species[] = [
  {
    id: 'lettuce-butterhead',
    name: 'Butterhead Lettuce',
    ideal_ec: 1.4,
    ideal_spectrum_rgb: [180, 40, 220],
    total_days: 45,
    base_growth_rate: 2.8,
    description: 'Fast-growing leafy green. Thrives under high red-blue spectrum. Ideal for beginners.',
    icon: '🥬',
  },
  {
    id: 'basil-genovese',
    name: 'Genovese Basil',
    ideal_ec: 1.8,
    ideal_spectrum_rgb: [200, 60, 180],
    total_days: 60,
    base_growth_rate: 2.2,
    description: 'Aromatic herb with high nutrient demand. Responds well to balanced R:B ratio.',
    icon: '🌿',
  },
  {
    id: 'tomato-cherry',
    name: 'Cherry Tomato',
    ideal_ec: 2.4,
    ideal_spectrum_rgb: [220, 50, 160],
    total_days: 90,
    base_growth_rate: 1.6,
    description: 'Fruiting crop requiring higher EC and extended photoperiod. Advanced growers.',
    icon: '🍅',
  },
  {
    id: 'spinach-bloomsdale',
    name: 'Bloomsdale Spinach',
    ideal_ec: 1.6,
    ideal_spectrum_rgb: [170, 50, 200],
    total_days: 40,
    base_growth_rate: 2.5,
    description: 'Cold-tolerant leafy green. Prefers cooler temperatures and moderate spectrum.',
    icon: '🍃',
  },
  {
    id: 'strawberry-albion',
    name: 'Albion Strawberry',
    ideal_ec: 1.8,
    ideal_spectrum_rgb: [210, 45, 170],
    total_days: 120,
    base_growth_rate: 1.2,
    description: 'Day-neutral variety. Requires careful spectrum management for fruiting phase.',
    icon: '🍓',
  },
  {
    id: 'kale-lacinato',
    name: 'Lacinato Kale',
    ideal_ec: 2.0,
    ideal_spectrum_rgb: [190, 55, 190],
    total_days: 55,
    base_growth_rate: 2.0,
    description: 'Hardy brassica with high nutrient density. Tolerates spectrum variations well.',
    icon: '🥗',
  },
];
