import { Species } from '../types';

export const seedSpecies: Species[] = [
  {
    id: 'lettuce-butterhead',
    name: 'Butterhead Lettuce',
    ideal_ec: 1.4,
    ideal_spectrum: [220, 60, 180, 20],
    total_days: 45,
    base_growth_rate: 2.8,
    description: 'Fast-growing leafy green. Thrives under high red-blue spectrum with low FR to prevent bolting. Ideal for beginners.',
    icon: '🥬',
    category: 'leafy',
    is_system: true,
  },
  {
    id: 'basil-genovese',
    name: 'Genovese Basil',
    ideal_ec: 1.8,
    ideal_spectrum: [200, 80, 160, 40],
    total_days: 60,
    base_growth_rate: 2.2,
    description: 'Aromatic herb with high nutrient demand. Moderate FR promotes branching and essential oil production.',
    icon: '🌿',
    category: 'herb',
    is_system: true,
  },
  {
    id: 'tomato-cherry',
    name: 'Cherry Tomato',
    ideal_ec: 2.4,
    ideal_spectrum: [240, 40, 120, 80],
    total_days: 90,
    base_growth_rate: 1.6,
    description: 'Fruiting crop requiring higher EC. High R/FR ratio during vegetative stage, increased FR triggers flowering.',
    icon: '🍅',
    category: 'fruiting',
    is_system: true,
  },
  {
    id: 'spinach-bloomsdale',
    name: 'Bloomsdale Spinach',
    ideal_ec: 1.6,
    ideal_spectrum: [160, 80, 220, 10],
    total_days: 40,
    base_growth_rate: 2.5,
    description: 'Cold-tolerant leafy green. Blue-dominant spectrum with minimal FR for compact growth and delayed bolting.',
    icon: '🍃',
    category: 'leafy',
    is_system: true,
  },
  {
    id: 'strawberry-albion',
    name: 'Albion Strawberry',
    ideal_ec: 1.8,
    ideal_spectrum: [230, 50, 140, 60],
    total_days: 120,
    base_growth_rate: 1.2,
    description: 'Day-neutral variety. Requires red-heavy spectrum with moderate FR for continuous flowering and fruiting.',
    icon: '🍓',
    category: 'fruiting',
    is_system: true,
  },
  {
    id: 'kale-lacinato',
    name: 'Lacinato Kale',
    ideal_ec: 2.0,
    ideal_spectrum: [180, 100, 200, 25],
    total_days: 55,
    base_growth_rate: 2.0,
    description: 'Hardy brassica with balanced spectrum needs. Low FR keeps leaves thick and nutrient-dense.',
    icon: '🥗',
    category: 'leafy',
    is_system: true,
  },
];
